### ISSUE TITLE
CORS Missing Allow Origin

### ISSUE THREAD

**Issue by sailendra2017** [tradzero/laravel-echo-redis-socketio#12]
Hi 
I am facing follwoing COR missing Allow Origin issue as follows: Can you help me ?
![image](https://user-images.githubusercontent.com/25950585/104031731-22f02b80-51f3-11eb-9c4e-fb8a149dfbd6.png)

**Comment by tradzero** [comment]
@sailendra2017 sorry for reply this so latey, this project is too old and not maintaining, but i try this in my mac, it runs well,
 and i found when i run `laravel-echo-server init`,  it seems provide cors settings.  
Here is my `laravel-echo-server.json` file. you can refer to this.
```json
{
	"authHost": "http://localhost",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"secureOptions": 67108864,
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"subscribers": {
		"http": true,
		"redis": true
	},
	"apiOriginAllow": {
		"allowCors": true,
		"allowOrigin": "http://localhost:80",
		"allowMethods": "GET, POST",
		"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
	}
}
```

**Comment by sailendra2017** [comment]
@tradzero Thanks for your replay.I am using following steps to resolve my issue and its working for me

> 
> 
> @sailendra2017 sorry for reply this so latey, this project is too old and not maintaining, but i try this in my mac, it runs well,
> and i found when i run `laravel-echo-server init`, it seems provide cors settings.
> Here is my `laravel-echo-server.json` file. you can refer to this.
> 
> ```json
> {
> 	"authHost": "http://localhost",
> 	"authEndpoint": "/broadcasting/auth",
> 	"clients": [],
> 	"database": "redis",
> 	"databaseConfig": {
> 		"redis": {},
> 		"sqlite": {
> 			"databasePath": "/database/laravel-echo-server.sqlite"
> 		}
> 	},
> 	"devMode": true,
> 	"host": null,
> 	"port": "6001",
> 	"protocol": "http",
> 	"socketio": {},
> 	"secureOptions": 67108864,
> 	"sslCertPath": "",
> 	"sslKeyPath": "",
> 	"sslCertChainPath": "",
> 	"sslPassphrase": "",
> 	"subscribers": {
> 		"http": true,
> 		"redis": true
> 	},
> 	"apiOriginAllow": {
> 		"allowCors": true,
> 		"allowOrigin": "http://localhost:80",
> 		"allowMethods": "GET, POST",
> 		"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
> 	}
> }
> ```

**Comment by sailendra2017** [comment]
@tradzero Thanks for your replay, i am using following steps to resolve my issue.

**Steps to resolve "CORS Missing Allow Origin" Error for your Echo Server on Windows 10 with XAMPP**

**STEP-1:** Add "transports: ['websocket', 'polling', 'flashsocket'] // Fix CORS error!" Code inside your Echo Server Setup File (public\js\laravel-echo-setup.js) like following code:

**window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001',
    transports: ['websocket', 'polling', 'flashsocket'] // Fix CORS error!
});**

**STEP-2:** Build Your Code Using "npm run dev" command Restart your Laravel Echo Server Using "laravel-echo-server start" command Now check your application, You can't find a CORS error now.
